### ISSUE TITLE
breaking changes in v1.7.0 without notice - no migration path given

### ISSUE THREAD

**Issue by talbx** [springwolf/springwolf-core#1000]
**Describe the bug**
Public APIs such as the `AsyncAnnotationScanner` were removed / altered in a breaking manner.
In the [release notes for v1.7.0](https://github.com/springwolf/springwolf-core/releases/tag/v1.7.0) nothing is mentioned regarding this.
A migration path for consumers of those changed / deleted public classes is missing.

Upgrading to v1.7.0 (in my case from v1.6.0) is breaking the build.

**Dependencies and versions used**
`springwolf-core` version `1.7.0`.

**Code example**
See this commit fa63e49f02a27762c38b49fd6f25251e08676b98.
Multiple classes were deleted, multiple classes were moved into different packages, such as the `AsyncAnnotationProvider`

ps: my team is using e.g `AsyncAnnotationScanner` and `AsyncAnnotationProvider` to help supporting multi-spec async API in our project. For more info see https://github.com/springwolf/springwolf-core/issues/805

ps²: are u generally using semver? if yes then this release number should be re-evaluated
**Stack trace and error logs**

**Comment by timonback** [comment]
Hi @talbx,
Thank you for the feedback.

> Springwolf uses interfaces to allow to inject functionality at integration points. Springwolf provides default implementation, but those can be replaced. All default implementations are Spring managed beans, which can be overridden.
> Source: https://www.springwolf.dev/docs/configuration/customizing

We consider most public interfaces as public APIs (i.e. `ChannelScanner`). Any implementations (including beans) are considered internal, but can be adapted/used/replaced on your own risk.
While we update the implementation to improve Springwolf, we try to keep the public interfaces stable in minor releases and do not mention this explicitly in the release notes.

We welcome you to participate at Springwolf.
To avoid future changes, we are interested to hear about your use-case and whether you can upstream your changes so that others can benefit as well.

Also, we have started on #805. Feel free to comment, implement and/or test so that there is no need for private customization.

**Comment by talbx** [comment]
Hi @timonback, 

thanks for the feedback!

Well you are completely right, we should just stick to the interfaces 😄 .
Of course we didn't since we worked on the custom usecase (#805) and needed to use some beans directly. 

Since you started working on #805, we are pausing the upgrade to v1.7.0, because then our efforts become obsolete anyway.  I will clarify in which manner we can assist you; e.g with further input or actual code contributions.
 
This issue can be closed then!

Thank you!

**Comment by timonback** [comment]
Hi @talbx,
a first preview of #805 is implemented. More details: https://github.com/springwolf/springwolf-core/issues/805#issuecomment-2465314764

We are looking forward to your feedback
