### ISSUE TITLE
Springwolf autoconfiguration

### ISSUE THREAD

**Issue by stavshamir** [springwolf/springwolf-core#128]
After removing the need for the docket and adding the property `springwolf.enabled`, I would expect as a user that the `@EnableAsyncApi` would not be required to enable springwolf..

**Comment by timonback** [comment]
Just checked, but noticed that the annotation is used to activate the component scanning as well: `@ComponentScan(basePackages={"io/github/stavshamir/springwolf"})`.

Not sure if there is a better way to activate the component scanning.

**Comment by tvahrst** [comment]
Yes, this is possible. A spring boot autoconfiguration can itself contain a `@ComponentScan`.

This would make the usage of springwolf much easier because defininig an empty (!) configuration class to add `@EnableAsyncApi` wouldn't  be necessary any more. If I decide to use springwolf in my project, adding it (e.g. one of the concrete plugins) to the dependency list should suffice.

**Comment by sam0r040** [comment]
@tvahrst Thanks a lot for your first contribution, great work!

**Comment by timonback** [comment]
The new version of springwolf has been released. Thank you @tvahrst for the contribution
