### ISSUE TITLE
AsyncAPI 2.6.0

### ISSUE THREAD

**Issue by Pakisan** [springwolf/springwolf-core#156]
Hey!

I released new version of library and created PR to update it in your project.

Everything works good except examples tests. I think that main reason is docker image to test with.

Need help to figure out why tests for examples are not working now

**Comment by Pakisan** [comment]
I found reason: I changed `int` to `Integer`, so here is no more default `0` in fields

**Comment by sam0r040** [comment]
Hi @Pakisan , thanks for your contribution. 

I see that the tests ApiIntegration*Tests are failing for the kafka example project. For me it looks like this is mostly because  the bindingVersion is always included in the specification, even if there is nothing documented. This seems to be only the case for Operation and Message Binding. I think this was added in the version you are updating to. Before it was possible to just use an empty Binding instance even if there was no code that would lead to a Binding being documented and an empty json object would be serialized for the Binding. I will need to have closer look to figure out a good solution.

For the issue with the expiration, I see that we the expiration is already covered by `@AmqpAsyncOperationBinding`, but the consumer side is not (as you said expiration is part of `com.rabbitmq.client.AMQP.BasicProperties`). The[ AsyncApi Spec](https://github.com/asyncapi/bindings/blob/master/amqp/README.md#operation-binding-object) currently says that expiration is for Publishing AND Subscribe, although I am wondering if a consumer could really define the TTL of received messages. Is it even possible to configure TTL for consumers within spring-rabbit?

Anyway, there for this specific issue, I see the a potential fix in `io.github.stavshamir.springwolf.asyncapi.serializers.AmqpOperationBindingSerializer#serialize`, as it seems to be a general problem within the class (and potential elsewhere). 

```JAVA
    @Override
    public void serialize(AMQPOperationBinding value, JsonGenerator gen, SerializerProvider provider) throws IOException {
        gen.writeStartObject();

        gen.writeNumberField("expiration", ofNullable(value.getExpiration()).orElse(0) );

        if (value.getCc() != null) {
            gen.writeArrayFieldStart("cc");
            for (String cc : value.getCc()) {
                gen.writeString(cc);
            }
            gen.writeEndArray();
        }

        gen.writeNumberField("priority", ofNullable(value.getPriority()).orElse(0));
        gen.writeNumberField("deliveryMode", ofNullable(value.getDeliveryMode()).orElse(0));
        gen.writeBooleanField("mandatory", ofNullable(value.getMandatory()).orElse(false));
        gen.writeBooleanField("timestamp", ofNullable(value.getTimestamp()).orElse(false));
        gen.writeBooleanField("ack", ofNullable(value.getAck()).orElse(false));

        gen.writeEndObject();
    } 
```

Dealing with the nullability, fixes the issue, but I feel that its not even a quick fix. Maybe it would be better to not write them in the spec if there is no value set.

I will probably discuss more with @timonback next week.

**Comment by Pakisan** [comment]
Hi @sam0r040!

I agree with proposed fix. Wrote same logic today at night to fix tests

> Dealing with the nullability, fixes the issue, but I feel that its not even a quick fix. Maybe it would be better to not write them in the spec if there is no value set.
> 
> I will probably discuss more with @timonback next week.

Will wait until you decide. I'm ready to implement the strategy which is more comfortable for your project

**Comment by sam0r040** [comment]
@timonback and me had a look at the issues with the custom serializers and removed them to get rid of the issue with null values. See https://github.com/springwolf/springwolf-core/pull/157 for the change. 

We also adapted your branch to the change and created a PR for it: https://github.com/Pakisan/springwolf-core/pull/1 
You can either rebase your branch to include those changes or we can merge your changes through the branch on Timons fork: https://github.com/timonback/springwolf-core/tree/feat/asyncapi_2.6.0

What would you prefer?

**Comment by Pakisan** [comment]
Hi @sam0r040 sorry for late response. 

Will update PR till end of this week.

> TTL is currently not supported in springwolf and will therefore not be documented. This would be a great contribution in case someone wants to work on it.

If you are ok with example above, I can create new PR for TTL

**Comment by Pakisan** [comment]
> @timonback and me had a look at the issues with the custom serializers and removed them to get rid of the issue with null values. See https://github.com/springwolf/springwolf-core/pull/157 for the change.
>
>We also adapted your branch to the change and created a PR for it: https://github.com/Pakisan/springwolf-core/pull/1
You can either rebase your branch to include those changes or we can merge your changes through the branch on Timons fork: https://github.com/timonback/springwolf-core/tree/feat/asyncapi_2.6.0

I merged your changes - https://github.com/Pakisan/springwolf-core/pull/1

**Comment by timonback** [comment]
Perfect.
PR looks good to me as well, builds are passing. Is the PR ready to be merged, as it is still in status "Draft"?

**Comment by Pakisan** [comment]
@timonback hi!

If you checked all and everything is ok, it can be merged.

I marked it as draft because of broken tests, which were fixed

**Comment by timonback** [comment]
Thank you for the contribution and updating the springwolf asyncapi spec version to 2.6.0!
