### ISSUE TITLE
Gradle compiler error for springwolf-core 0.11.0

### ISSUE THREAD

**Issue by hirth-abi** [springwolf/springwolf-core#232]
**Describe the bug**

After upgrading springwolf-core to 0.11.0, Gradle logs the listed compiler error. The compilation still succeeds.

**Dependencies and versions used**

implementation "io.github.springwolf:springwolf-core:0.11.0"
runtimeOnly "io.github.springwolf:springwolf-ui:0.8.0"

**Stack trace and error logs**

```
Errors occurred while build effective model from .../.gradle/caches/modules-2/files-2.1/io.github.springwolf/springwolf-core/0.11.0/1329cd32162c64d095a250a0769d21f63e283355/springwolf-core-0.11.0.pom:
	  'dependencies.dependency.version' for io.swagger.core.v3:swagger-models-jakarta:jar is missing. in io.github.springwolf:springwolf-core:0.11.0
```

**Comment by timonback** [comment]
@sam0r040 and me analyzed this yesterday. While we are not able to reproduce this exactly, we stumbled in another project over
`[WARNING] The POM for io.github.springwolf:springwolf-core:jar:0.11.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details` when building with maven.

We believe the issue is that the `version` attribute is not set for all dependencies.
And the underlying issue being relying on gradle dependency management (versions being managed in `dependencies.gradle`) which is not picked up when generated the releaseMaven artifact (including the pom file).

**Comment by timonback** [comment]
Latest snapshot build contains the version field for all dependencies (except spring ones): https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/springwolf/springwolf-core/0.11.0-SNAPSHOT/springwolf-core-0.11.0-20230625.220629-2.pom

**Comment by maksymgendin** [comment]
<img width="1240" alt="image" src="https://github.com/springwolf/springwolf-core/assets/3966758/10f177b2-3125-48f1-ba80-c97132e75354">

This is probably a consequential error due to the versions error in springwolf-core?

**Comment by timonback** [comment]
Thank you for the report @maksymgendin 

Are you (@maksymgendin and/or @hirth-abi) able to verify whether the current snapshot version resolves the issue?
You will need to use the `-SNAPSHOT` version AND add the snapshot maven repo as mentioned in the README.md: https://github.com/springwolf/springwolf-core#development
(Updated docs: https://github.com/springwolf/springwolf-core/pull/245/files )

FYI: We are preparing a patch release: https://github.com/springwolf/springwolf-core/pull/244

**Comment by sam0r040** [comment]
Thanks for verifying the fix. We will push forward with a patch release then.

**Comment by timonback** [comment]
Thank you for the reports. The patch release is available now.

**Comment by maksymgendin** [comment]
@timonback Sorry for the late reply. Runtime works as well, thanks for the fix ❤️
