### ISSUE TITLE
Springwolf-ui Path Conflict

### ISSUE THREAD

**Issue by kaant2** [springwolf/springwolf-core#365]
Springwolf-ui declared as
![image](https://github.com/springwolf/springwolf-core/assets/135351505/7af6f3af-f454-4ad3-adff-63826ed7e84a)
In springwolf.dev website. The path is `https://demo.springwolf.dev/springwolf-ui/asyncapi-ui.html` in demo. As you see, there is a conflict on `/springwolf` part between doc and demo. It's not a big deal, I know, but you can print the springwolf-ui on console for preventing confusion.

**Comment by timonback** [comment]
Hi @kaant2,
the website shows the real springwolf-ui, however with a mocked backend. Therefore, the urls differ - also due to how GitHub pages handles sites for repos.

With "print the springwolf-ui [path] on console", you probably refer to the springwolf application start. At this point I am not sure, if we can detect whether the springwolf-ui project is also part of the application as it is its own dependency.

Feel free to contribute.
