### ISSUE TITLE
Kafka Topics with Specific Schema Type Payloads Incorrectly Represented in Spec

### ISSUE THREAD

**Issue by jenarp** [springwolf/springwolf-core#377]
**Environment:**

Springwolf UI version: 0.14.0
Browser: Chrome 116.0.5845.187
Operating System: macOS Ventura 13.4.1

**Description:**

When using Springwolf to define Kafka topics, there's a limitation regarding the payload types. Specifically, while I can configure my own payload classes with `@Schema` annotations for documentation, there's an issue when the payload is of specific schema types, including but not limited to primitive types, arrays, email, UUID, and more. I want to have the ability to set those types as payloads but still have the option to attach `@Schema` annotations for documentation purposes.

**Steps to Reproduce:**

- Set up a Kafka topic in Springwolf with e.g. a primitive payload type (String).
- Attempt to attach a `@Schema` annotation for documentation.
- Observe that while custom payload classes support annotations, specific schema types do not.

**Expected Behaviour:**

All schema types should allow the attachment of `@Schema` annotations for detailed documentation and be accurately represented in the spec.

**Actual Behavior:**

Specific schema types cannot be attached with `@Schema` annotations and are not represented correctly in the spec (and in the UI).

**Additional Details:**

In my current implementation, I've created a workaround for this limitation. However, having this feature natively supported in Springwolf would be beneficial for many users.

**Potential Impact:**

Without this feature, users might have to resort to convoluted methods or miss out on documenting specific schema types properly, leading to potential misinterpretations or misuse of the Kafka topics.

**Suggested Fix:**

- Broaden the Springwolf logic to accommodate a wider range of `Schema<?>` objects as payload types.
- Ensure that these schemas are correctly rendered and documented in the spec.

**Comment by timonback** [comment]
Hi @jenarp ,

Thank you for the report.
I am not sure if I fully understand your report.

Can you give a code example?
Are you adding the `@Schema` annotation to the listener method - since you can't add the annotation to the primitive type String (same for array, etc)

Current workaround is to define your own Payload class.

**Comment by jenarp** [comment]
Hi @timonback,

Sure! Let me clarify my use-case.

I am setting up an `AsyncApiDocket`:

```
@Bean
@Nonnull
public AsyncApiDocket asyncApiDocket() {
    final Info info = Info.builder()
        .version("1.0.0")
        .title("Kafka")
        .description("description")
        .build();

    final KafkaProducerData explicitSchemaProducer = KafkaProducerData.kafkaProducerDataBuilder()
        .topicName("topic 1")
        .description("description")
        // Desired functionality illustrated below:
        .payloadType(/* I aim to use a type like String here and also provide an example via @Schema annotations*/)
        .build();

    return AsyncApiDocket.builder()
        .info(info)
        .servers(servers)
        .producer(explicitSchemaProducer)
        .build();
}

```

My challenge is with the `.payloadType()` method. Ideally, I'd like to specify a simple string type as its value, but I also want the flexibility to annotate that string with `@Schema` for documentation purposes.

With the current setup, if I use a custom class to encapsulate the string (as a workaround) and annotate that class with `@Schema`, the resulting example in the specification gets wrapped in curly braces, as if it's an object, rather than being represented as a plain string.

Swagger indeed offers constructs like `StringSchema()` that derive from `Schema()`. These constructs allow the necessary annotations for documentation, and they ensure the correct representation in the specification. It would be extremely beneficial if Springwolf's payloadType method could natively support or be compatible with `Schema<?>` types, ensuring both the right documentation and representation.

I hope this provides a clearer picture.

**Comment by jenarp** [comment]
I believe I understand your suggestion: wrapping the string within a payload object that contains a string attribute?

While this is a good solution in many contexts, unfortunately, our project has specific constraints: we need to directly place primitive types into the Kafka topic. 
Additionally, I think that in the spec, the type is categorised as 'object' rather than 'string', though I'm not entirely certain.

**Comment by timonback** [comment]
Thanks @jenarp that helps.

Yes, the workaround is creating a new class and wrapping the primitive and true, that modifies the contract.

I do recommend using the application.properties together with the AsyncPublisher annotation instead of the AsyncApiDocket, but your described issue exists there as well.

The payloadType in the AsyncListener annotation is used to override the auto-detected type. I can imagine that we add a field to explicitly set/override the schema manually - i.e. in https://github.com/springwolf/springwolf-core/blob/master/springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/AsyncOperation.java
Why adding? Because we cant specify the type class<?> and schema<?> in one field.

Still, I am open for any suggestions/improvements/other solutions.

Can you imagine to create an (initial) Pull-Request to support your use-case?

**Comment by timonback** [comment]
Hi @jenarp,

We thought about different solutions and have come up with a potential solution.

The idea is to continue to use the `payloadType` field of the `AsyncPublish/Subscribe` annotation. Since a primitive field (like String) can't be documented directly, an envelope class is created (similar to the work-around with the List<> generic). To indicate the payload field, a new annotation (i.e. `@AsyncApiPayload`) is searched for. In case exactly one annotation is found, that field is used as the payload.

Example code:

```java
@AsyncPublisher(operation = @AsyncOperation( ..., 
        payloadType = Envelop.class,
))
public void sendMessage(ExamplePayloadDto msg) {
        ...
}

class Envelop {
      @AsyncApiPayload
      @Schema(name = "payload-full-name", ...)
      private String payload = new String();
}
```

What are your thoughts? Does it solve your problem?

**Comment by jenarp** [comment]
It seems like a good idea at first sight, and I think it could work out.
However, I'm wondering about the possibility of providing multiple examples. Is it possible to create an additional Envelope Class that includes a different example? When using the docket, I could add multiple Producers each with unique Payload Examples. Although ultimately everything is a string, the content varies significantly, and I'd like to document these differences. If it's only possible to have one example, though, I'm okay with that limitation.

**Comment by timonback** [comment]
To document multiple payloads, the `@AsyncPublisher` annotation can be specified multiple times on the same method - while specifying the `payloadType` property to indicate the different payloads, like:
```java
@AsyncPublisher(operation = @AsyncOperation( ..., 
        payloadType = Envelop1.class,
))
@AsyncPublisher(operation = @AsyncOperation( ..., 
        payloadType = Envelop2.class,
))
public void sendMessage(ExamplePayloadDto msg) {
        ...
}
```

We will go ahead then with the implementation of the proposal to indicate the actual payload of an envelop class using the `@AsyncApiPayload` or similar annotation.

**Comment by timonback** [comment]
Thank you for the report, the issue has been addressed in the new release. See the release notes and/or documentation for more details.

Feel free to reopen this issue if there is still something missing.
