### ISSUE TITLE
Spring Cloud Stream consumer with parameterised type not returning the correct payload type

### ISSUE THREAD

**Issue by SheheryarAamir** [springwolf/springwolf-core#433]
**Describe the bug**
I am facing another issue, where I am expecting MyEvent as payload type but instead I am getting org.springframework.messaging.Message as payload type which is wrong

below is the signature of my consumer 
```
@Bean
    public Consumer<Message<MyEvent>> consumeEvent() {
    }
 ```

**Dependencies and versions used**
`springwolf-cloud-stream` version `0.6.1`.

**Code example**
```
@Bean
    public Consumer<Message<MyEvent>> consumeEvent() {
    }
 ```

**Stack trace and error logs**
N/A

**Comment by timonback** [comment]
Hi @SheheryarAamir,
as mentioned above, we are not sure that we found the best solution in #441.

Still, we wanted to include this in Springwolf 0.17.0, therefore the current solution is included and marked as beta.
More details soon on the website or in https://github.com/springwolf/springwolf.github.io/pull/65

To avoid changing behaviour, we kept `List` as part of the defaults.

Thank you for opening the issue and starting on the PR.
We would love to hear from you if this resolves your issue and what is not optimal yet so that we can improve.

**Comment by SheheryarAamir** [comment]
Thank you @timonback. Yes, solution implemented in version `0.17.0` partly resolve my issue as we are able to extract payload type in case it is wrapped in spring `Message` interface. But current version does not support custom interfaces e.g 
`MyInterface<String>`

**Comment by timonback** [comment]
Great.
Have you tried the new configuration documented at https://www.springwolf.dev/docs/configuration/documenting-messages#unwrapping-the-payload ?
Instead of the java util Function, you will have to use your own fully qualified class name.

**Comment by SheheryarAamir** [comment]
Thank you @timonback. Its working, able to extract payload type from custom interface.
