### ISSUE TITLE
@RabbitListener scanning still supporting?

### ISSUE THREAD

**Issue by GoodDonkey** [springwolf/springwolf-core#60]
I tried several times with rabbit listener but channels was not recognized by spring-wolf.
the `http://localhost:8081/springwolf/asyncapi-ui.html` opens up fine, showing Server and Info, but not Channels.
In RabbitMQ Management console, channels are fine with each queue name

I did with springwolf 0.4.0, 0.3.1 but I found that documentation states that latest support for RabbitMQ is 0.2.0
So, tried with 0.2.0, some implementations being different(i.e. basePackage() doesn't exist in AsyncApiDocket), also not applicable.

additionally, I cannot find any debug log after this:
`......i.g.s.s.asyncapi.DefaultAsyncApiService  : Building AsyncAPI document`

any test being done lately??

**Comment by stavshamir** [comment]
Hi, I believe you might have used the wrong dependency - springwolf has different plugins and the kafka plugin is version 0.4.0, while the rabbit one is indeed version 0.2.0. 
Please make sure you are using the following:
```groovy
dependencies {
    // Provides the documentation API    
    implementation 'io.github.springwolf:springwolf-amqp:0.2.0'

    // Provides the UI - optional (recommended)
    runtimeOnly 'io.github.springwolf:springwolf-ui:0.3.1'
}
```
you can see a complete example here https://github.com/springwolf/springwolf-core/tree/master/springwolf-plugins/springwolf-amqp-plugin#usage

Please let me know if your issue is solved.

**Comment by GoodDonkey** [comment]
oh Instantly solved the problem. sorry for bothering you. thank you for the answer and the plugin!!

**Comment by stavshamir** [comment]
You're welcome :)
