### ISSUE TITLE
Add support for YAML format

### ISSUE THREAD

**Issue by milehimikey** [springwolf/springwolf-core#65]
Feature request to add yaml format to the `/springwolf/docs` endpoint. This can be useful for certain tools that work from YAML files to render AsyncAPI documentation.

**Comment by Crain-32** [comment]
See https://stackoverflow.com/questions/58414715/generate-yaml-format-response-in-springboot for possible solution for integration.
You'd just have to have a second `@GetMapping` that produces the normal `json`.

**Comment by Crain-32** [comment]
After Review, this is not a proper feature request for Springwolf due to the following reasons.

- As an imported Library, Springwolf should not affect any expected Spring Configuration. This would either require forcing users to use Jackson specifically, or creating a new Add-on for each Message Mapping based on user requests.
- YAML is not an [officially supported MIME Type](https://www.iana.org/assignments/media-types/media-types.xhtml), as such any support is left to the discretion of the Development Team.
- Enabling YAML for a single endpoint would provide a conflicting user experience, and be very hard to do without enabling YAML Server-wide.

@milehimikey I would recommend looking into [this](https://blog.jdriven.com/2016/11/handling-yaml-format-rest-spring-boot/) guide for enabling a custom `HttpMessageAdapater` to handle an `accept: "application/yaml" header (Which would also enable YAML input in Request Bodies) If you want to solve this Server side.
Regarding YAML file tools, all JSON Files are valid YAML Files, and any inability to parse JSON should be considered an issue in that tool.


@stavshamir feel free to close this Issue.

**Comment by stavshamir** [comment]
Json could be easily translated to yaml with external tools. Maybe this can be added as a feature for the UI in the future as an export button.
